---
- name: Add the user '{{ developer_username }}' with the {{ developer_uid }} uid and a primary group of 'developer'
  user:
    comment: Unknown Developer
    name: "{{ developer_username }}"
    uid: "{{ developer_uid }}"
    groups: [sudo]
    shell: /bin/bash
  register: developer_user_info

- name: Set developer_username to exist user
  set_fact:
    developer_username: "{{ developer_user_info.name }}"

- name: Change user password
  user:
    name: '{{ developer_username }}'
    update_password: always
    password: "{{ developer_password | password_hash('sha512') }}"

- name: Allow root password login via ssh
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.*PermitRootLogin.*$'
    replace: 'PermitRootLogin yes'

- name: Dissalow root password login via ssh
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.*PasswordAuthentication.*$'
    replace: 'PasswordAuthentication no'

- name: 'Set ClientAliveInterval to 3600'
  lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'ClientAliveInterval 3600'

- name: Restarting sshd
  set_fact:
    service_restarted: "{{ service_restarted + [ 'sshd' ] }}"

- name: Installing git-ssh
  copy:
    src: files/bin/git-ssh
    dest: /usr/local/bin/git-ssh
    owner: root
    mode: u=rwx,g=rx,o=rx

- name: Ensure ownerships
  file:
    dest: "{{ developer_user_info.home }}"
    owner: "{{ developer_username }}"
    recurse: true
  when: developer_user_info.home is regex('^/home/.*')
