---
- name: Disable ipv6
  lineinfile:
    dest: '/etc/sysctl.conf'
    line: '{{ item }}'
  with_items:
    - 'net.ipv6.conf.all.disable_ipv6 = 1'
    - 'net.ipv6.conf.default.disable_ipv6 = 1'
    - 'net.ipv6.conf.lo.disable_ipv6 = 1'

- name: Update apt cache
  apt: 
    update_cache: yes

- name: Install base packages
  apt:
    pkg: "{{ base_packages }}"
    state: present

- name: Download PUP {{ pup_version }}
  get_url:
    url: https://github.com/ericchiang/pup/releases/download/{{ pup_version }}/pup_{{ pup_version }}_linux_amd64.zip
    dest: /tmp/pup_{{ pup_version }}_linux_amd64.zip

- name: Extract PUP {{ pup_version }}
  unarchive:
    src: /tmp/pup_{{ pup_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: True
    mode: 0755
    owner: root
    group: root
